// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var c = 10;

console.log(10);

var myString = "Hello, world!";

var output = String(10) + " " + myString;

console.log(output);

var a = 5;

var b = 5;

var d = "String";

var myInteger = 10;

exports.a = a;
exports.b = b;
exports.c = c;
exports.d = d;
exports.myInteger = myInteger;
exports.myString = myString;
exports.output = output;
/*  Not a pure module */
